#
# Make a javascript for handling the solidity contracts, use the abi and bin files in the generated
# directory.
#
# Copyright (c) 2017 Tomas Stenlund (dnulnets)
#
cd generated
echo "//" > contract.js
echo "// Generated javascript file from abi and bin files generated by the solidity compiler." >> contract.js
echo "//" >> contract.js
echo "// Copyright (c) 2017, Tomas Stenlund (dnulnets)" >> contract.js
echo "//" >> contract.js
echo "" >> contract.js
echo "var ConsentContract = function (web3) {" >> contract.js
for entry in *.abi
do
    echo "  this."${entry%.abi}" = web3.eth.contract ("`cat $entry`");" >> contract.js
    echo "  this."${entry%.abi}"Binary = \"0x"`cat ${entry%abi}bin`"\";" >> contract.js
done
echo "}" >> contract.js
echo "" >> contract.js
echo "module.exports = ConsentContract" >> contract.js
